var ui={
	line:[
		{
			confele:"color",
			dom:"input",
			type:"color"
		},
		{
			confele:"width",
			dom:"input",
			type:"range",
			range:{
				min:1,
				max:48,
				step:1
			}
		},
		{
			confele:"opacity",
			dom:"input",
			type:"range",
			range:{
				min:1,
				max:100,
				step:1
			}
		}
	],
	direct:[
		{
			confele:"color",
			dom:"input",
			type:"color"
		},
		{
			confele:"width",
			dom:"input",
			type:"range",
			range:{
				min:12,
				max:48,
				step:1
			}
		},
		{
			confele:"opacity",
			dom:"input",
			type:"range",
			range:{
				min:1,
				max:100,
				step:1
			}
		},
		{
			confele:"style",
			dom:"select",
			select:["follow","center","hover","ui_bottom"]
		}
	],
	tip:[
		{
			confele:"color",
			dom:"input",
			type:"color"
		},
		{
			confele:"bgcolor",
			dom:"input",
			type:"color"
		},
		{
			confele:"width",
			dom:"input",
			type:"range",
			range:{
				min:12,
				max:48,
				step:1
			}
		},
		{
			confele:"opacity",
			dom:"input",
			type:"range",
			range:{
				min:1,
				max:100,
				step:1
			}
		},
		{
			confele:"style",
			dom:"select",
			select:["follow","center","hover","ui_bottom"]
		},
		{
			confele:"withdir",
			dom:"input",
			type:"checkbox"
		}
	],
	note:[
		{
			confele:"color",
			dom:"input",
			type:"color"
		},
		{
			confele:"width",
			dom:"input",
			type:"range",
			range:{
				min:12,
				max:48,
				step:1
			}
		},
		{
			confele:"opacity",
			dom:"input",
			type:"range",
			range:{
				min:1,
				max:100,
				step:1
			}
		},
		{
			confele:"style",
			dom:"select",
			select:["follow","center","hover","ui_bottom"]
		}
	],
	allaction:[
		{
			confele:"color",
			dom:"input",
			type:"color"
		},
		{
			confele:"bgcolor",
			dom:"input",
			type:"color"
		},
		{
			confele:"width",
			dom:"input",
			type:"range",
			range:{
				min:12,
				max:48,
				step:1
			}
		},
		{
			confele:"opacity",
			dom:"input",
			type:"range",
			range:{
				min:1,
				max:100,
				step:1
			}
		},
		{
			confele:"style",
			dom:"select",
			select:["follow","center","hover","ui_bottom"]
		}
	]
}
var menuModel={
	fn:["general","mges","sdrg","drg","rges","wges","pop","icon","ctm"/*"wges","rges","sfn"*/],
	main:["general","mges","sdrg","drg","rges","wges","pop","icon","ctm",/*"sfn","apps",*/"about"],
	general:["setting","fnswitch","searchmgr","scriptmgr","linux","per","conf"],
	mges:["setting","ui","gesmgr"],
	sdrg:["setting","tsdrg","lsdrg","isdrg"],
	drg:["setting","ui","tdrg","ldrg","idrg"],
	rges:["action"],
	wges:["action"],
	pop:["setting","action"],
	icon:["setting","action"],
	ctm:["setting","action"],
	sfn:["settings"],
	apps:["settings"],
	about:["about","translate","thanks",/*"help",*/"changelog"]
}